function data()
return { 
		["vehicle/waggon/ibes/icons/ibes_bell_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_bell_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_bell_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_bell_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_bell_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_chiquita_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_chiquita_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_chiquita_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_chiquita_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_chiquita_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_de_graaf_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_de_graaf_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_de_graaf_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_de_graaf_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_de_graaf_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_frigo_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_frigo_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_frigo_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_frigo_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_frigo_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_alt_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_alt_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_alt_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_alt_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_alt_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_fs_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_gkf_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_gkf_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_gkf_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_gkf_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_gkf_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if2_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if2_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if2_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if2_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if2_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_if_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros2_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros2_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros2_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros2_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros2_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_migros_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb2_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb2_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb2_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb2_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb2_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sbb_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sncb_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sncb_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sncb_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sncb_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_sncb_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef2_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef2_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef2_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef2_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef2_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef_icon20@2x.tga"] = { 
			channels = 4,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef_icon20_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 34, 20, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef_icon_small_cblend@2x.tga"] = { 
			channels = 1,
			extent = { 94, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/ibes_stef_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/menu_ibes_icon_small@2x.tga"] = { 
			channels = 4,
			extent = { 182, 56, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/icons/menu_ibes_store.tga"] = { 
			channels = 4,
			extent = { 311, 207, },
			numMipmaps = 1,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_albedo.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_alt_albedo.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_mga.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_nrml.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_bell.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_chiquita.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_degraaf.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_frigo.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_fs.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_fsalt.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_gkf.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_if.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_if2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_migros.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_migros2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_sbb.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_sbb2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_sncb.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_stef.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_stef2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_dca.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_mga.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_nrml.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_sbb_mga.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_sbb_nrml.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 0,
		},
	}
end