function data()
return { 
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_albedo.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_alt_albedo.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_mga.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/drehgestelleinzeln_nrml.dds"] = { 
			channels = 4,
			extent = { 1024, 1024, },
			numMipmaps = 11,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_bell.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_chiquita.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_degraaf.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_frigo.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_fs.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_fsalt.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_gkf.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_if.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_if2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_migros.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_migros2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_sbb.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_sbb2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_sncb.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_stef.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_albedo_stef2.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_dca.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_mga.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_nrml.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_sbb_mga.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
		["vehicle/waggon/ibes/mat/tex/ibes_sbb_nrml.dds"] = { 
			channels = 4,
			extent = { 2048, 2048, },
			numMipmaps = 12,
			numStrippedMipmaps = 1,
		},
	}
end